### ISSUE TITLE
有sql文件吗

### ISSUE THREAD

**Issue by fengyue9** [hcbkq/-ERP#1]

**Comment by hcbkq** [comment]
很久了应该不见了吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月14日(周日) 下午4:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [hcbkq/-ERP] 有sql文件吗 (Issue #1)




 
Closed #1 as not planned.
